name: Pull Request Processing
on:
  pull_request:
    types: [opened]
jobs:
  process_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Python script
      run: python injectHelloWorld.py

